### ISSUE TITLE
Damage is not received

### ISSUE THREAD

**Issue by confus-3d** [Move38/DragonsLair#4]
Hi there.

Tried the actual version in master and also the finalChanges.

In master version, everything is working, in finalChanges the damage is not beeing received while minning.
I think is because byte neighbor[6]; 

Also, **in both versions**, once minned, you can stay attached there all the time you want until deattach 
This is because ignoredFaces[face] = 1;
and then ignoredFaces[f] = 0; when there is no neighbor.

Maybe instead of ignoring faces on player is better ignore faces on sending while treasure respawn?

What do you think?

**Comment by confus-3d** [comment]
SOLVED:

Remove the **following code** to be able to receive an attack while still conected, keep _this code_:

  if (blinkType == PLAYER) {
    if (luck < 1) {
      isDead = true;
    }
    //listen for damage
    FOREACH_FACE(f) {
      if (!isValueReceivedOnFaceExpired(f)) {//a neighbor!
        if (getBlinkType(getLastValueReceivedOnFace(f)) == FIELD) {
          if (getAttackSignal(getLastValueReceivedOnFace(f)) == FIRE || getAttackSignal(getLastValueReceivedOnFace(f)) == POISON) {
            **if (ignoredFaces[f] == 0) {//take damage            __________REMOVE**
              _takeDamage(f);    _____________//KEEP_
            **}             ___________REMOVE**
          }
        }
      **} else {
        ignoredFaces[f] = 0;     __________MAYBE INNECESARY???, IS ALREADY ON THE NEXT FUNCTION
      }**
    }

**This solution is NOT working on the version with byte neighbor[6];**

**Comment by confus-3d** [comment]
SOLVED:

I've managed to fit everything in both versions, whith this changes: 
-Removed **byte neighbor[6];** not working propperly (it saves space but it doesnt work)
-Keep Impact Display
-Removed **(ignoredFaces[f] == 0)** and changed for **if (takingDamage == false) {** Now you can receive UP TO one hit if you don't remove, it resets when is alone.
-Changed **waitTime = map** (for a simpler equation that saves some space)
-Removed innecesary **if (isAlone()) {** when selecting player (save some space)
-Receive damage loop integrated on mining loop (saves space)

Everything else working 100%

Here is the fork, please compare to see changes! =D:
https://github.com/confus-3d/DragonsLair/blob/master/DragonsLair/DragonsLair.ino

I also made a pull request (no idea what it is, i'm new in GitHub) =D

**Comment by ReluctantPirate** [comment]
Solved by Francisco
